application: little-black-box
version: gitcommithash
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /api/.*
  script: gae.main.APPLICATION

- url: /task/.*
  script: gae.task.APPLICATION
  login: admin

- url: /bootstrap
  static_dir: bootstrap

- url: (/|/oauth2callback)
  static_files: app/index.html
  upload: app/

# Must be last
- url: /
  static_dir: app


# https://developers.google.com/appengine/docs/python/config/appconfig#Inbound_Services
inbound_services:
- channel_presence


# See https://developers.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Skipping_files
skip_files:
# Built-in defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom entries
- ^(.*/)?.*/node_modules/.*$
